projects:
  productivitytracker:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        graphQLApiId: m5lrlpwdazbmhjgbzo6h7qzol4
      endpoints:
        prod: >-
          https://4eq5d72dazg3tnwkme2dfj4nxq.appsync-api.us-east-1.amazonaws.com/graphql
